name: Fly Deploy
on:
  push:
    branches: ["prod"] # adapt branch for project
  pull_request:
    branches: ["prod"] # adapt branch for project

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"
