services:
  db:
    image: postgres:12
    ports: ["5432:5432"]
    env:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
